[build-system]
requires = ["pdm-backend >= 2.4.0"]
build-backend = "pdm.backend"

[project]
name="cal"
version="0.2"
description="produces annual wall calendars"
authors=[
   { name="Dr. Joerg Fischer", email="georgi.rybakov@gmx.net" } ]
readme="README.md"
requires-python = ">=3.13"
license = "MIT"
dependencies=[
   "pyexiv2",
   "python-dateutil",
   "reportlab"
]

[project.urls]
Homepage = "https://github.com/raumanzug/cal"
